### ISSUE TITLE
start_epoch, end_epoch and payment_amount should be numbers, not strings

### ISSUE THREAD

**Issue by UdjinM6** [dashevo/proposal-generator#25]

**Comment by Alex-Werner** [comment]
Thank you for this one. 
Indeed by default jquery will always get a val() as string. Trivial fix here, will handle that ! 
Actually, If this is a constant rules, I should have that directly being handled in bitcore-lib-dash too then. 

So you are confirming that start_epoch, end_epoch and payment_amount that aren't number should be rejected right ?

**Comment by UdjinM6** [comment]
>So you are confirming that start_epoch, end_epoch and payment_amount that aren't number should be rejected right ?

Yes, we are going to fix dashd validators and sentinel code the same way.

**Comment by Alex-Werner** [comment]
Good, then indeed I have to handle the validators in bitcore-lib then, because right now it still allow it. 
Handling that ! 

Thank you :)

**Comment by chaeplin** [comment]
fyi :
12.2 has ```gobject check <data-hex>```. Can check a proposal without collateral submitting.

**Comment by Alex-Werner** [comment]
The problem here is that we are in a front place. So we can't use any check right now :/ 
I've implemented gobject list and get, but not check, it could be good to have that soon. 
In the meantime, we have a serialize check in bitcore-lib but it didn't take that into account
