### ISSUE TITLE
Serious flaw in the payment date calculator

### ISSUE THREAD

**Issue by jhodges10** [dashevo/proposal-generator#32]
![image](https://user-images.githubusercontent.com/18431344/36184374-2b883b2e-10e8-11e8-847c-f90302b68fda.png)

It is calculating superblock dates wrong right now and may set people up for failure.

**Comment by nmarley** [comment]
Hey @jhodges10 , thanks for reporting. Looks like you've clicked the testnet tab. Can you check if this is an issue once you click the "mainnet" tab just above and to the right of the "Create a Proposal" header?

**Comment by jhodges10** [comment]
Okay phew. It's working fine in mainnet.

I got thrown off because I didn't chose testnet and assumed default would be mainnet.

**Comment by nmarley** [comment]
Hey Jeff, so I double-checked and it looks like it the default should be mainnet also:

https://github.com/dashevo/proposal-generator/blob/4c3a6560bd25a92fd3918c05327e287551d1662c/index.html#L141
https://github.com/dashevo/proposal-generator/blob/4c3a6560bd25a92fd3918c05327e287551d1662c/js/index.js#L14
https://github.com/dashevo/proposal-generator/blob/4c3a6560bd25a92fd3918c05327e287551d1662c/js/index.js#L48

Not sure why yours went to mainnet, but glad it's sorted now, thanks again.
